version: "3.7"

services:
    nginx:
        container_name: mlm-site-nginx
        image: nginx:latest
        ports:
            - "${DOCKER_NGINX_PORT}:80"
            - "${DOCKER_NGINX_PORT_SSL}:443"
        networks:
            - site
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx/
            - ./storage:/storage
            - ./public/docs:/public/docs
        depends_on:
            - php

    php:
        container_name: mlm-site-php
        build:
            context: ./
            dockerfile: docker/fpm/Dockerfile
        working_dir: /api
        expose:
            - "9000"
        networks:
            - site
        restart: always
        volumes:
            - ./.:/api
        environment:
            PHP_IDE_CONFIG: "serverName=${DOCKER_PROJECT_DOMAIN}"
        depends_on:
            - redis

    db:
        container_name: mlm-site-db
        image: mysql:latest
        volumes:
            - site-db-vol:/var/lib/mysql
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        command: [
            "--log_bin_trust_function_creators=1",
            "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        ]
        ports:
            - "${DOCKER_PROJECT_IP}:${DOCKER_DB_PORT}:3306"
        networks:
            - site
        restart: always

    redis:
        container_name: mlm-site-redis
        image: redis:7-alpine
        ports:
            - "${DOCKER_PROJECT_IP}:6379:6379" # опционально, если нужно подключаться извне
        networks:
            - site
        restart: always
        volumes:
            - redis-data:/data

    rabbitmq:
        image: rabbitmq:3-management
        container_name: ${DOCKER_CONTAINER}-rabbitmq
        ports:
            - "5672:5672"    # RabbitMQ
            - "15672:15672"  # Web UI http://localhost:15672
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - site

networks:
    site:
        driver: bridge

volumes:
    site-db-vol:
    redis-data:
